
services:
  todo-list:
    build: ./
    ports: 
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
        restart: true
    
  db:
    restart: always
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mainpet
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
    ports:
      - 5436:5432