version: '3.8'

services:
  todo-list:
    build: ./
    command: ./main
    ports: 
      - 8080:8080
    depends_on:
      db: 
        condition: service_healthy
        restart: true
    

  db:
    restart: always
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mainpet
    ports:
      - 5432:5432