
services:
  todo-list-http:
    build: ./
    ports: 
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    
  db:
    restart: always
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./.database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mainpet
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
    ports:
      - 5436:5432
  redis:
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 6380:6379
    volumes:
      - ./.redis_data:/data
