srv:
  port: 8080

db:
  host: db
  port: 5432
  username: postgres
  dbname: mainpet
  sslmode: "disable"

redis:
  addr: redis:6379
  db: 0

kafka:
  broker: 
  - kafka:29091
  consumerGroup: mainpet